### PR TITLE
Update language_de.ini

### PR DESCRIPTION
**Pull request by in60dev**
Fix translation issiue

Change 

label_filament_runout:Filament alle!

to 

label_filament_runout:Filament leer!

Also reportet in repo bigtreetech/BIGTREETECH-TouchScreenFirmware

### CODE REVIEW

**Comment by discip** [comment]
@in60dev
Unfortunately this is no a fix.

The current state is correct, as "**alle**" in German would translate to something like _"**there is no more**"_.

However "**leer**" means "**empty**". The filament itself can't get empty, the spool can!

In German there is a difference between the two, so please don't confuse them. 😊

So either keep "**Filament alle!**" or change it to _"**Filamentspule leer!**"_. But by no means ~"Filament leer!"~.

**Comment by in60dev** [comment]
Okay, that's right! 
The spool is empty and not the filament.
It should read "Filament spool empty!"
I've correct it

**Comment by kisslorand** [comment]
I am not sure "Filament spool empty!" is OK. Filament sensor is there to let the printer know if there's filament fed to the extruder or not. There can be several other reasons why filament is not fed to the extruder like a jammed extruder, filament snapped on the spool (happened to me with old PLA) and so on...

What do you think about "Mangel an Filament!"?

**Comment by in60dev** [comment]
What do you think about "Filament prüfen"?
Various errors would have been covered here.

**Comment by kisslorand** [comment]
My German language knowledge is limited but it sounds adequate. What do you think about "Filamentfehler"?
Whatever you decide is OK as long as it fits for the purpose of the filament sensor.

**Comment by in60dev** [comment]
I've updated the commit.
I think "Filament prüfen!" is a good choice.
You have the attention that the filament should be checked, but there does not have to be an error.

**Comment by kisslorand** [comment]
Yes, you're right! Thanks for the corrections made.

**Pull request merged**
